tpm2-software/tpm2-pytss

- setup.py
When tpm2-tss is installed to the standard include files directory `/usr/include`, `pkg-config --cflags` filters out this system directory, leading to an empty output. SWIG on the other hand does not search `/usr/include` by default, which leads to the error
```
swig -python -py3 -outdir tpm2_pytss -o tpm2_pytss/swig/esys_binding_wrap.c tpm2_pytss/swig/esys_binding.i
tpm2_pytss/swig/tpm2_types.i:8: Error: Unable to find 'tss2/tss2_common.h'
tpm2_pytss/swig/tpm2_types.i:9: Error: Unable to find 'tss2/tss2_tpm2_types.h'
error: command 'swig' failed with exit status 1
```
Setting the environment variable `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` disables the filtering, thus adding the required `-I/usr/include` to the SWIG call.
> setup.py: always add include files directory for SWIG

- MANIFEST.in
[`examples/fapi_get_random.py`](https://github.com/tpm2-software/tpm2-pytss/blob/master/examples/fapi_get_random.py) is required by [`tests/test_examples.py`](https://github.com/tpm2-software/tpm2-pytss/blob/master/tests/test_examples.py) and might be helpful for users as well. Examples are only included in the distribution and not installed by Python.
> MANIFEST: distribute examples

- .ci/download-deps.sh
- examples/fapi_get_random.py
- tpm2_pytss/util/testing.py
Since upstream commit https://github.com/tpm2-software/tpm2-tss/commit/e974a73b087c8889a3d138b09fbe71031ed9f8b8 it is necessary to use `ek_cert_less` when testing with the TPM simulator since the EK is now used as a session key by default and the TPM simulator does not provide an EK certificate.
> tests: use ek_cert_less for mssim FAPI tests for tpm2-tss 2.4.1

- tpm2_pytss/context.py
For return types which consist of `uint8_t*` and `size_t`, the `to_bytearray` arguments need to be swapped.
To verify this, issue a FAPI`PcrRead` command
```python
with UINT8_PTR_PTR() as pcrValue:
with SIZE_T_PTR() as pcrValueSize:
with CHAR_PTR_PTR() as pcrLog:
pcrValue, pcrLog = fapi_ctx.PcrRead(0, pcrValue, pcrValueSize, pcrLog)
print(str(pcrValue))
```
> Fix return type for uint8_t array

- examples/fapi_get_random.py
- tests/test_esys_audit.py
- tests/test_esys_auto_session_flags.py
- tests/test_esys_get_capability.py
- tests/test_esys_get_random.py
- tests/test_esys_get_time.py
- tests/test_esys_load_external.py
- tests/test_fapi_get_random.py
- tests/test_tcti.py
- tpm2_pytss/binding.py
- tpm2_pytss/context.py
- tpm2_pytss/esys.py
- tpm2_pytss/tcti.py
- tpm2_pytss/util/swig.py
I made a bad decision when going with context managers. My paranoia that things wouldn't get free'd was, well, too much paranoia for that. This patchset uses `__del__`, which is a sane approach.
This patchset also includes auto allocating of arguments which hold return values
> refactor: No context managers

- tpm2_pytss/context.py
Fix two issues.
A) context.py handles function input parameters.
`UINT<n>_T` are special because for their pointer type `UINT<n>_PTR`, the __T_
suffix is omitted. That's not the case with all other types, including
`SIZE_T`, the pointer type of which is _SIZE_T_PTR_.
context.py accounts for the `uint<n>_t` special case. However, this code
path is also matches for _size_t_ types, treating them as a special case,
too, when they are in fact not.
B) In some cases, when NULL/None is returned, a cast to a byte array fails. Add a check.
> Fix size_t pointer args

- tpm2_pytss/ESAPI.py
- tpm2_pytss/TctiLdr.py
With this ectx = ESAPI() works
> esapi: don't assume caller is providing TCTI context.

- scripts/libtss2_build.py
- setup.cfg
Use `pkgconfig` to get the include paths for the libraries. This also works for manually installed libraries (`/usr/local`).
Also, the build script `libtss2_build.py` gave me a TypeError, so I had to move the `debug=True`
I was not to sure how to add `pkgconfig` as a dependency. Would that be in `.ci/Dockerfile.tpm2-tss-python` or `.ci/download-deps.sh`?
**NOTE**: This PR sits on top of #58.
> Use pkgconfig to discover include paths

- test/TSS2_BaseTest.py
Class TSS2_BaseTest was added twice, remove one of the definitions
keeping the one with pass on setUp and tearDown.
> test: drop duplicate TSS2_BaseTest class

- tpm2_pytss/types.py
Make the ffi.new functions classes, so we have all the powers of
classes. For not we can just hook the class instantation function
__new__ to instantiate ffi specific classes. Later if we need something
more powerful, we will have full control over the class if needed.
> types: make ffi.new functions classes

- test/test_exception.py
- tpm2_pytss/TSS2_Exception.py
- tpm2_pytss/utils.py
This is a more or less a cut and paste from the previous bindings.
Useful when debugging and could be used to provide better feedback/error messages from applications to users.
> utils: parse TSS2 return code in exception

- scripts/libtss2_build.py
- scripts/prepare_headers.py
- tpm2_pytss/TSS2_Exception.py
Use Tss2_RC_Decode to get the string representation of the error and
display it, plus fall back to 0x<RC> if for some reason the call fails.
Also drop the Long string, since the exception stacks and traces are
descriptive enough. It makes it too long.
Was:
tpm2_pytss.TSS2_Exception.TSS2_Exception: TSS2 Library call failed with: 0x70018
Is now:
tpm2_pytss.TSS2_Exception.TSS2_Exception: esapi:The ESYS_TR resource object is bad
> TSS2_Exception: plumb to tss2-rc

- test/test_fapi.py
Each FAPI test needs to be run in its own subprocess because it [exports the `TSS2_FAPICONF`](https://github.com/tpm2-software/tpm2-pytss/blob/e32432f691eb26aaa31603c0d29427a36fdcbc8f/tpm2_pytss/FAPI.py#L78) (a.k.a. [`FAPI_CONFIG_ENV`](https://github.com/tpm2-software/tpm2-pytss/blob/e32432f691eb26aaa31603c0d29427a36fdcbc8f/tpm2_pytss/FAPI.py#L15)) environment variable to point to its own temporary FAPI configuration. Not isolating the tests in different subprocesses leads to errors like
```
if self.config is None:
config_path = os.environ.get(FAPI_CONFIG_ENV, FAPI_CONFIG_PATH)
>           with open(config_path) as file:
E           FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3e2_8a4c'
```
because the next test tries to set up the configuration from the environment …
> test: mark FAPI tests as @pytest.mark.forked

- scripts/libtss2_build.py
The header file was missing, leading to compilation warnings like
```
build/temp.linux-x86_64-3.6/tpm2_pytss._libtpm2_pytss.c:38178:10: warning: implicit declaration of function 'Tss2_RC_Decode'; did you mean 'Tss2_Sys_Quote'? [-Wimplicit-function-declaration]
```
and `test_exception.py` crashing with a segmentation fault on my system.
> script/libtss2_build.py: add tss2-rc header file

- test/test_types.py
- tpm2_pytss/types.py
This enables things like TPMS_NV_PUBLIC(nameAlg=TPM2_ALG.SHA256)
> types.py: support setting struct/union fields during initialization

- .ci/Dockerfile.tpm2-tss-python
- setup.cfg
We mount the git repo through using -v in docker commands, no need to
explicitly copy the contents into the Docker Image.
> Dockerfile: drop COPY of local workspace

- test/test_types.py
- tpm2_pytss/types.py
Rather than needing to write code to handle every TPML initialization,
since thier is only count and one other field, make it smarter and have
it figure out how to initialize objets in one of three conditions:
- _cdata is specified
- kwargs is specified using the field value to set
- they just passed data into the constructor:
_cdata is set but NOT with CFFI CData.
> types: make TPML_* init smarter

- test/test_esapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
- tpm2_pytss/utils.py
William Roberts (13):
ESAPI: test IncrementalSelfTest
ESAPI: test StartAuthsession for HMAC
TPM2_OBJECT: support simpler initializations
ESAPI: set session1 ESYS_TR.PASSWORD
ESAPI: add TRSess_SetAttributes
ESAPI: test StartAuthSession with tpmKey
Catch when type is string, ffi.error is returned
TPM2B_ make types even smarter
types: make TPML_ types smarter
ESAPI: support StartAuthSession with tpmKey and bindKey
types: don't hide typerror
types: drop commented out code
types: TPM2B_ add bytes and str methods for all TPM2B types
> more tests and type enhancements

- test/test_esapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
William Roberts (6):
ESAPI: test StartAuthSession w/nonceCaller
ESAPI: test Create
ESAPI: test load
ESAPI: test ReadPublic
TPML_OBJECT: make iterable
types: get rid of all remnants of unpacker
> ESAPI Tests (StartAuthSession, Create, Load, Readpublic) and Implement Test TPML iteration

- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
* Makes the size attribute read only
* Keeps track of buffer size when buffer is changed
* Makes buffer data inmutable
* Makes the class indexable, iterable and sliceable
I had to change unrelated tests as they where using TPM2B_DIGEST
> types.py: add TPM2B_OBJECT to handle size + buffer structures

- test/test_types.py
- tpm2_pytss/types.py
LGTM issued the following warning:
`NEWCall to self.__setattr__ in __init__ method, which is overridden by method TPM2B_SIMPLE_OBJECT.__setattr__.`
The help document for the issue is:
https://lgtm.com/rules/10030085/
LGTM's help document was clear that we should avoid this paradigm. In
this case it worked fine, but lets minimize warnings and bad patterns
when possible.
> LGTM: fix constructor calling subclass method

- .ci/run.sh
- .github/workflows/tests.yaml
- Drop codecov token from the secrets, its not needed.
- Cleanup exports into the env variable for Github Actions.
- Make the run.sh script use an argument over magic env variable.
> Drop codecov token

- test/test_crypto.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
public_to_pem and public_from_pem will work directly on a TPMT_PUBLIC object.
I kept toPEM and fromPEM on TPM2B_PUBLIC as well as it's useful
Related to https://github.com/tpm2-software/tpm2-pytss/issues/88
> types.py / crypto.py: move toPEM / fromPEM to TPMT_PUBLIC

- .ci/Dockerfile.tpm2-tss-python
- .ci/Dockerfile.tpm2-tss-python-black
- .ci/run.sh
- .github/workflows/publish_docs.yaml
- .github/workflows/publish_pkg.yaml
- .github/workflows/tests.yaml
- create a publish package job and limit it to PUSH TAG events.
- set the SSH account for publishing docs to github pages branch to not @pdxjohnny.
- make testing the docs for PR's and PUSH requests only run the sphinx command (scripts/docs.sh)
- make publishing docs it's own job and limit to PUSH events.
> more ci changes

- .ci/docker-prelude.sh
- .ci/docker.run
- .ci/download-deps.sh
- .readthedocs.yml
- docs/conf.py
- docs/requirements.txt
- docs/sphinx-finished.sh
- scripts/docs.sh
- scripts/prepare_headers.py
- setup.cfg
- test/TSS2_BaseTest.py
- test/test_crypto.py
- test/test_esapi.py
- test/test_fapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/FAPI.py
- tpm2_pytss/TctiLdr.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
- tpm2_pytss/utils.py
I switched to readthedocs, but it's broken. The build fails to include ESAPI do to an import error, thus we Mock things since we cant pull external dependencies onto RTD build servers.
Also deal with:
- Fix SPDX identifiers
- sphinx-rtd-theme
> fix sphinx build for readthedocs

- tpm2_pytss/ESAPI.py
- tpm2_pytss/__init__.py
Currently, CData can come from two sources:
1. allocated via ffi.new
2. allocated from a successful call to ESAPI API as returned via the
double pointer interface.
Item one does not pose an issue, as it will use matching allocator and
deallocator routines.
Item 2 is tricky. Be default (AFAIK[1]), the pointer of the pointer will also be
handled by CFFI's free function. However, that can cause issues where
ESAPI is allocating with one implementation and cffi is deallocating
with another non-abi compatible issue. This issue can be seen with the
introduction of Esys_Free and is notably an issue on Windows.
Thus we need to explicitly, and ONLY for ESAPI allocations, set the
explicit free function. I recieved help from the mailing list[1] for cffi
on how to design this, and tested it by …
> ESAPI: free types properly

- test/test_crypto.py
- test/test_esapi.py
- tpm2_pytss/ESAPI.py
* Allows bytes instead of TPM2B_SIMPLE_OBJECT instances
* Allows None as a parameter when allow_none=True (see inPrivate for LoadExternal)
* Checks for either the correct TPM_OBJECT instance type or the correct ffi cdata instance type
The current tests uses LoadExternal in test_crypto.py and Vendor_TCG_Test which is a bit weird, I can always add more specific tests if it's wanted.
Had to add the get_cdata function to ESAPI.py instead of utils.py as types.py imports utils.py
> ESAPI.py: add function to check input parameter types

- tpm2_pytss/ESAPI.py
@williamcroberts, as requested.
I'm writing tests for NV_ChangeAuth and NV_Certify, after that I'll add check_handle_type to all the other NV-tests and do some small cleanups.
> test_esapi.py: add parameter name to get_cdata exceptions

- tpm2_pytss/callbacks.py
- tpm2_pytss/constants.py
> fixup SPDX identifiers from BSD-3 to 2

- tpm2_pytss/ESAPI.py
Also remove one TPM2B_pack from NV_Write.
With this I think all the NV calls are in a good state
> ESAPI.py: check handles for all NV calls

- test/test_esapi.py
- tpm2_pytss/ESAPI.py
Needed by TSSPrivKey and some tests.
> ESAPI.py: add TR_FromTPMPublic method

- .gitignore
- setup.cfg
- test/test_esapi.py
- test/test_fapi.py
- tpm2_pytss/ESAPI.py
- test: FAPI fix tests against master
- test: fix FAPI generate_private_key() missing argument: 'backend'
- test: FAPI fix load_pem_public_key() missing 'backend'
- test: FAPI fix __init__() missing argument: 'backend'
- test: ESAPI PolicyRestart
- test: FAPI fix __init__() missing argument 'backend'
- test: ESAPI StartAuthSession with bad nonce
- ESAPI: StartAuthSession nonceCaller should be TPM2B_NONCE
- test: ESAPI Shutdown
- gitignore: pycoverage htmlcov report dir
- gitignore: .rej and .orig patch files
> more esapi testing

- test/test_esapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
- test: ESAPI PolicyGetDigest
- test: ESAPI PolicyCommandCode
- test: ESAPI PolicyAuthValue
- test: ESAPI Duplicate
- types: add iterator and contains to friendly int
> ESAPI Testing PolicyGetDigest, PolicyCC, PolicyAuth, and Duplicate

- setup.cfg
- test/test_crypto.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
With this most common formats/encodings are supported directly, not just PEM encoded public keys.
I also added cryptography to install_requirements.
> Add support for pure DER encoded keys and certificates

- test/test_crypto.py
- test/test_esapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
- tpm2_pytss/utils.py
ESAPI: update CreatePrimary API
Make CreatePrimary interface:
- not need PCR data, default empty
- not need creation data, default empty
- creation data since it's a pcr selection supports pcr selection
strings.
- not need hierarchy, default owner
- support tpm2-tools like initializer strings for TPM2B_PUBLIC
- Defualt name alg SHA256
- Default attribute set
It will stillr require the sensitive portion so folks have to explicitly
opt in to no passwords.
Additional Notes:
I did initially code this in a way where the get_cdata, on getting passed a string, if the current class object didn't have a parse routine, would look at the subfields and if only one subfield other than size existed, instantiate that, get the cdata and then use than call that subclass's parse method. While more generic, …
> Esapi testing (Quote) and API changes to CreatePrimary and Create Plus lots of checks/tests added

- test/test_crypto.py
- test/test_esapi.py
- tpm2_pytss/ESAPI.py
This sets the following defaults for the NV API:
* Owner as the hierarchy for (Un)DefineSpace and GlobalWriteLock
* Platform as the hierachy for UndefineSpaceSpecial
* nvIndex as the authHandle for all read/write operations (including {Read,Write}Lock)
* offset to 0 for read operations
> Normalize NV API

- test/test_crypto.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
If we support pure DER for public keys we should probably support it for private keys as well.
Also move fromPEM to TPMT_SENSITIVE
> crypto.py: add support for pure DER encoded private keys

- test/test_crypto.py
- test/test_makecred.py
- tpm2_pytss/crypto.py
- tpm2_pytss/makecred.py
This will add a MakeCredential implementation without the need for a TPM (simulator) and lay the foundation for the duplicate protocol
> add python MakeCredential implementation

- tpm2_pytss/crypto.py
Fixes errors like:
def private_key_from_encoding(data):
sdata = data.strip()
key = None
if sdata.startswith(b"-----BEGIN RSA PRIVATE KEY-----") or sdata.startswith(
b"-----BEGIN EC PRIVATE KEY-----"
):
key = load_pem_private_key(sdata, password=None)
else:
try:
>               key = load_der_private_key(data, password=None)
E               TypeError: load_der_private_key() missing 1 required positional argument: 'backend'
> crypto: fix missing backend argument

- tpm2_pytss/FAPI.py
FAPI provision can fail with already provisioned, which is OK. However,
the _chkrc function takes a list of acceptable RC's to check against
before raising the exception. However, FAPI provision passed just an
int, not a list and generates the following error:
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:1473:Fapi_Provision_Finish() ErrorCode (0x00060025) No EK certifcate found for current crypto profile found. You may want to switch the profile in fapi-config or set the ek_cert_less or ek_cert_file options in fapi-config. See also https://tpm2-software.github.io/2020/07/22/Fapi_Crypto_Profiles.html
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:168:Fapi_Provision() ErrorCode (0x00060025) Provision
Traceback (most recent call last):
File "a.py", line 4, in <module>
fapi.provision()
File …
> FAPI: fix provision acceptable rcs

- test/test_esapi.py
- test/test_types.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/types.py
- tpm2_pytss/utils.py
Also, make getitem of a TPML_* of TPM2B_SIMPLE objects return the bytes themselves over the wrapper.
> Esapi testing (PolicySecret and PolicyTicket)

- test/test_types.py
- tpm2_pytss/types.py
Simply pass the comparison to an instance of bytes
> types: add equal comparison method for TPM2B_SIMPLE_OBJECT

- test/test_fapi.py
- tpm2_pytss/FAPI.py
type is a reserved symbol in python, thus one shouldn't assign to it.
PEP8 guidelines dictate we should place an underscore on reserved names,
thus type becomes type_.
> FAPI: fix use of assignment to reserved symbol type

- test/test_types.py
- tpm2_pytss/types.py
tpm2-tools has it own format to store context data and I find it useful to combine the python bindings and the tools
> Add method to load key context generated by tpm2-tools

- docs/requirements.txt
- test/test_fapi.py
- tpm2_pytss/FAPI.py
- tpm2_pytss/utils.py
@williamcroberts as promised, I added tpm2-tss version checks to the FAPI. If there is a bug (which we had problems with in the past), a warning will be logged. The tests will be skipped accordingly.
I checked for all this bugs for which release branches they were fixed. For one bug I there was no PR so I did a git bisect.
Please take a look at `check_bug_fixed(fixed_in="3.2", backports=["2.4.7", "3.0.5", "3.1.1"], ...)`:
* bug is fixed if the current version is affected by fix on master branch, here if version >= `3.2`
* if not, check backports, for example if current version is `2.4.8`
* `2.4.8` matches backport `2.4.x` and `.8` >= `.7` -> bug is fixed
Does this sound reasonable?
Fixes #169
> FAPI: add TSS bug checking/warnings to FAPI

- test/test_esapi.py
- tpm2_pytss/ESAPI.py
> ESAPI: start_auth_session default nonce_caller to None

- test/test_crypto.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
Both RSA and ECC private keys can provide the public key so this enables from_pem in TPMT_PUBLIC/TPM2B_PUBLIC on private keys.
> crypto: add support for getting the public part from private keys

- test/test_crypto.py
- tpm2_pytss/crypto.py
- tpm2_pytss/types.py
The reason for only having the keyedhash_from_secret method on TPMT_SENSITIVE / TPM2B_SENSITIVE is that the private and public parts are very interconnected.
I'm not 100% sure about this API, so some feedback would be appreciated.
Especially the seed value handling is a bit icky, I'm not sure that all zeros is a sane default or if it should be random.
After working out the API I'll do something similar for symmetric ciphers.
> [RFC] types: add support for loading HMAC keys and seal data from bytes

- tpm2_pytss/ESAPI.py
None is an instance, not a type
> esapi: fix TCTI check in ESAPI init

- docs/fapi.rst
- test/TSS2_BaseTest.py
- test/test_fapi.py
- test/test_tcti.py
- tpm2_pytss/FAPI.py
- tpm2_pytss/TCTILdr.py
- tpm2_pytss/__init__.py
- tpm2_pytss/utils.py
Changes:
* rename api files and classes to uppercase (pep8), as discussed in #54
* add optional size param to `FAPI.create_seal()`
* test Fapi against both RSA and ECC
* account for yet another bug in fapi: tpm2-software/tpm2-tss/issues/2092
Fixes #54
The tests are still brittle because they test against the system FAPI configs (and the defaults are assumed). This should not be a showstopper for the first release, though. Also, the documentation can be improved, for sure. However, to get this shipped, I'd say FAPI is ready for release. 
Edit: Fyi, I'm gonna be on leave the following week.
> Make FAPI ready for release

- tpm2_pytss/makecred.py
Default the symkey to None, which will cause a key to be generated if
symdef is not None or not TPM2_ALG.NULL.
Default the symdef to aes128cfb which is the spec default protection
algorithm.
This way calls omitting the symdef and symkey will generate a wrapping
key and use aes128cfb be default.
> wrap: simplify input parameters

- docs/index.rst
pytss now uses CFFI instead of SWIG, supports Python 3.9, and no longer uses recursive git submodules. Update the documentation accordingly.
> docs: update instructions

- .ci/install-deps.sh
- HACKING.md
- docs/index.rst
- scripts/prepare_headers.py
- tpm2_pytss/ESAPI.py
- tpm2_pytss/FAPI.py
- tpm2_pytss/internal/crypto.py
- tpm2_pytss/internal/utils.py
- tpm2_pytss/tsskey.py
- tpm2_pytss/types.py
In ESAPI:
- Use `Optional` or `Union[..., None]` where a variable can be `None`.
- Fix the description of some functions, which was probably copy-pasted from other ones.
- Use `ESYS_TR.OWNER` instead of `TPM2_RH_OWNER`, and also for `ENDORSEMENT` and `PLATFORM`
- Uniformize `ESYS_TR.PLATFORM+{PP}` notation (for "Physical Presence")
While at it, fix many other misspellings in other files.
> Fix ESAPI Python types and comments, and many misspellings

- test/test_makecred.py
- test/test_types.py
- test/test_utils.py
- tpm2_pytss/internal/crypto.py
- tpm2_pytss/types.py
- tpm2_pytss/utils.py
Add the inverse operation of wrap, unwrap, which essentially allows for
TPM key exportation given a key with proper attributes. By duplicating
the key to a parent where one controls or has access to the private key,
the returned TPM2B_PRIVATE from the TPM2_Duplicate command can be
unwrapped into the TPMT_SENSITIVE. From there, folks can furlough that
key if needed, or use it in their favorite crypto lib.
> add an unwrap function

- test/test_crypto.py
- tpm2_pytss/types.py
With this both _SENSTIVE and _PUBLIC will have the same methods.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/267
> types: add to_der and to_ssh to {TPM2B,TPMT}_public

- setup.py
Fixes the type mapper when doing 32 bit (glibc) builds and add supports for unions in the type mapper (a good example for needing that is  TPMU_SYM_KEY_BITS)
> Preprocessor fix

- tpm2_pytss/types.py
The current comment to ignore it LGTM is incorrect, correct it to be of
the proper format for ignoring by LGTM.
> lgtm: ignore py/import-and-import-from

- setup.py
Generate type_mapping.py in the build directory and only copy it to the source directory if it's a inplace install.
With this both pip install and pip install -e will work
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/276
> setup: add fix for non-editable pip install

- docs/api.rst
- docs/constants.rst
- test/test_types.py
- tpm2_pytss/constants.py
- tpm2_pytss/types.py
Update the exceptions that the various parse routines can throw to use
ValueError and TypeError over the less specific RuntimeError and
document the inherited interfaces.
This is was kept as one commit since detangling it was more of a
headache than what it is worth (we wouldn't try and revert part of it).
> constants/types: update docs and exceptions

- docs/types.rst
- test/test_crypto.py
- test/test_types.py
- tpm2_pytss/internal/crypto.py
- tpm2_pytss/types.py
Document more of the types module and classes and update exception
classes used. ValueError should be used in most instances where
RuntimeError is being used with the exception of the MU lookup.
> types: add more documentation

- tpm2_pytss/ESAPI.py
- tpm2_pytss/internal/crypto.py
- tpm2_pytss/utils.py
Hello,
While seeing how to make the code compliant with `mypy --strict`, I stumbled upon misspellings in the code which were reported as:
```text
tpm2_pytss/ESAPI.py:6867: error: Name 'RunTimeError' is not defined
tpm2_pytss/utils.py:225: error: Name 'encdupsens' is not defined
```
This Pull Request fixes these misspellings.
EDIT: added a 3rd occurrence, found with `tpm2_pytss/internal/crypto.py:288: error: Name 'obj' is not defined`
> Fix misspellings in Python code

- test/test_esapi.py
- tpm2_pytss/internal/utils.py
- tpm2_pytss/types.py
When using one of the tpm2-tss deconstructors (Esys_Free and Fapi_Free)
the memory might be freed when there is no more reference to the root
field even when a sub-field is still used, leading to memory corruption.
This solves this by using a custom deconstructor for sub-fields which
keeps a reference to its parent
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/299
> types: ensure deconstructor order

- tpm2_pytss/types.py
Any errors when trying to import type_mapping should only be ignored during doc generation.
> types: add check for sphinx in type_mapping import

- tpm2_pytss/ESAPI.py
Several functions related to NV indexes take an optional parameter defined as `auth_handle: ESYS_TR = 0`. However the zero `ESYS_TR` is defined (it is `ESYS_TR.PCR0`) and in Python, such "default parameter value" usually uses `None`. Moreover using `None` helps checking the type annotations.
Make the functions use `None` instead of `0`.
Fixes: https://github.com/tpm2-software/tpm2-pytss/issues/297
> ESAPI: use None instead of 0 for default auth_handle

- test/test_fapi.py
- tpm2_pytss/ESAPI.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/305
> ESAPI: add check for bad type_/FAPI_CONTEXTLOAD value in load_blob

- .ci/install-deps.sh
In shell script, using `... pip>21.3` means "run the command and write the output in a file named `21.3`. This leads to empty output in GitHub Actions, such as in https://github.com/tpm2-software/tpm2-pytss/runs/4703569920?check_suite_focus=true#step:4:2004
Fix this by quoting the parameter, which makes the shell interpret it as a string instead of an output redirection.
> ci: quote the minimal version in pip command line

- tpm2_pytss/ESAPI.py
In ESAPI methods, some parameters were missing, others did not appear in the method declaration, there were some misspellings, and some functions were not associated with the correct one.
Fix all these issues. While at it, uniformize the documentation text a bit more (using `.` and `:` and spaces where appropriate).
> ESAPI: fix many issues in documentation

- test/test_types.py
- tpm2_pytss/constants.py
Fixes:
Make TPMA_CC a subclass of TPMA_FRIENDLY_INTLIST
str(TPMA_CC()) returning "commandindex_shift"
str(TPMA_NV.AUTHWRITE | ...) raising ValueError: unnmatched values left: 0x4
> constants: add fixes for tools-like string generation

- .ci/install-deps.sh
When using `sudo apt-get ...`, the environment variables are not forwarded by default. So in fact `apt-get` runs without
`DEBIAN_FRONTEND=noninteractive`. This triggers interactive prompts when running `.ci/install-deps.sh` in a Docker container.
Fix this by defining `DEBIAN_FRONTEND=noninteractive` directly in the `sudo` line.
> ci: define DEBIAN_FRONTEND correctly in apt-get

- test/test_esapi.py
- tpm2_pytss/ESAPI.py
When `ESAPI.close` is called twice, it could raise an exception:
>>> from tpm2_pytss import *
>>> ectx = ESAPI("tabrmd:bus_type=system")
>>> ectx.close()
>>> ectx.close()
WARNING:esys:src/tss2-esys/esys_context.c:114:Esys_Finalize() Finalizing NULL context.
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/workspace/tpm2-pytss/tpm2_pytss/ESAPI.py", line 155, in close
self._tcti.close()
Fix this by ensuring that `self._tcti` is not `None` before calling
`close`. While at it, do not call `Esys_Finalize` twice.
Fix a bug in the handling of the logic to close the TCTI in
ESAPI.close(). If a TCTI object is passed to ESAPI(), the close() method
on the TCTI is never invoked and the connection is never terminated,
thus subsequent calls will block as the TPM resource is …
> ESAPI: fix double-close issue

- test/test_utils.py
- tpm2_pytss/internal/templates.py
- tpm2_pytss/utils.py
I have tested the standard ECC and RSA templates towards a real TPM, but the the NV nonce/template is written according to the specification/tpm2-tools so I'm not 100% they work in real life.
Draft until I add types to arguments and documentation.
Related to https://github.com/tpm2-software/tpm2-pytss/issues/203
> utils: add function to generate an EK

- test/test_esapi.py
- tpm2_pytss/ESAPI.py
The binding for Esys_TR_GetTpmHandle is missing, add it and a test.
> ESAPI: add binding for Esys_TR_GetTpmHandle

- tpm2_pytss/internal/utils.py
- tpm2_pytss/types.py
Instead of letting the caller keep track of if they passed session_type and
auth_hash to to_tools to get a tpm2-tools session context object raise an
exception if session_type and auth_hash is missing when  savedHandle is is
in the HMAC or policy session ranges.
> types: add check in TPMS_CONTEXT.to_tools for session handles

- setup.cfg
Since commit 10d7b4811706de8dc01dd586fc7a0d4df4c1f17b ("replace runtime pkgconfig usage with a version table") pkgconfig is no longer required at runtime.
> setup.cfg: remove pkgconfig from install_requires

- setup.py
As FAPI support is optional just ignore missing pkgconfig packages.
Missing required ones will make build fail at an earlier stage.
> setup: ignore missing/failing pkgconfig files in version_table

- .github/workflows/tests.yaml
- setup.cfg
- test/TSS2_BaseTest.py
- tpm2_pytss/internal/utils.py
Drop 3.6 and add 3.10 with some fixes for distutils usage.
Also make sure the required version of cryptography is correct
> Python versions

- test/test_types.py
- tpm2_pytss/constants.py
- tpm2_pytss/types.py
Support SM2 and SM4 parsing in TPMT_PARSE, should behave as the tools.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/321 and https://github.com/tpm2-software/tpm2-pytss/issues/320
> SM2 and SM4 parsing

- docs/index.rst
- scripts/libtss2_build.py
- tpm2_pytss/utils.py
Some small fixes for the build scripts and documentation fixes.
With this it shouldn't be any issue building on a system where IBMs TSS is installed using the method @diabonas recommended
> Build script fixes

- test/test_internal.py
- tpm2_pytss/internal/utils.py
git describe ahead of tag has three parts:
- recent tag
- commits since recent tag
- current commit
- possibly a dirty flag if modified
Ignore these in version handling logic to fix:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/wcrobert/workspace/tpm2-pytss/installation/usr/lib/python3.8/site-packages/tpm2_pytss/__init__.py", line 2, in <module>
from .ESAPI import ESAPI
File "/home/wcrobert/workspace/tpm2-pytss/installation/usr/lib/python3.8/site-packages/tpm2_pytss/ESAPI.py", line 2, in <module>
from .types import *
File "/home/wcrobert/workspace/tpm2-pytss/installation/usr/lib/python3.8/site-packages/tpm2_pytss/types.py", line 23, in <module>
from tpm2_pytss.internal.crypto import (
File "/home/wcrobert/workspace/tpm2-pytss/installation/usr/lib/pytho …
> versions: fix git describe handling

- test/test_utils.py
- tpm2_pytss/internal/crypto.py
SM3 and SM4 support in cryptography was added after they switched to rust so there are some distributions that don't yet support  the rust bindings.
I'm not sure that this is the right way, but the alternatives are either skipping it or create problems for non-x86/ARM systems.
> Camellia, SM3 and SM4

- .ci/install-deps.sh
- test/test_encoding.py
tpm2-tools 5.3 fixed the wrong output of NV index attributes (cf. https://github.com/tpm2-software/tpm2-tools/issues/3053 and https://github.com/tpm2-software/tpm2-tools/commit/8ec91507a2ecb641e449eb1cd85b6fd67a265198), so the expected value in tpm2-pytss needs to be adjusted accordingly.
> test_encoding: fix expected NV attributes according to tpm2-tools 5.3 release

- README.md
The package was spelled tpm2-ptss insteak of tpm2-pytss, correct this mispelling.
> README: fix typo in pip install command

- test/TSS2_BaseTest.py
- test/test_utils.py
When the simulator doesn't support camellia, this exception is thrown and the test fails:
FAILED test/test_utils.py::TestUtils::test_make_credential_ecc_camellia - tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(2):unsupporte...
Fix it by skipping the test and also add a helper that when setting up the test framework also caches the supported algoirthms and has a helper for skipping tests when the TPM simulator lacks support.
> test: skip test when camellia not supported

- src/tpm2_pytss/ESAPI.py
Using 'type_' makes sphinx throw a warning/error.
Using 'type\_' will give a DeprecationWarning from python.
Using 'type\\_' Will make the inline documentation look weird.
Lets go with the last alternative.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/382
> docs: fix escape in ESAPI.load_blob

- src/tpm2_pytss/internal/crypto.py
- src/tpm2_pytss/utils.py
Rather than hardcoding CFB and ignoring mode, just use mode as returned from the lookup of symdef.
Other modes would cause a failure anyways.
> internal: use mode in _(encrypt|decrypt)

- .ci/run.sh
- scripts/get_deps.py
- setup.cfg
Ensure the CI builds the wheel and installs it and that all paths in the
module resolve and tests run.
related-to: #341
> ci: verify built wheel

- docs/conf.py
As readthedocs documentation generation uses the source tree and not a build, set fake versions to make sure that he version dependent parts are included in the public docs.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/466
> docs: use fake library versions for readthedocs

- src/tpm2_pytss/internal/crypto.py
- src/tpm2_pytss/types.py
- test/test_types.py
Make calling bytes(sig) return the underlying signature bytes. Useful to pass the signature to other APIs/libraries who don't use TPM structures.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/463
> types: add __bytes__ to TPMT_SIGNATURE

- src/tpm2_pytss/ESAPI.py
The check was that the ESYS_TR was a constant in the class, which is not true it could be for a transient or persistent handle, etc.
Fixes:
Traceback (most recent call last):
File "./edge-main.py", line 79, in <module>
e.policy_secret(phandle, session, nonce, b"", b"", 0)
File "/home/wcrobert/workspace/tpm2-pytss/src/tpm2_pytss/ESAPI.py", line 3991, in policy_secret
_check_friendly_int(auth_handle, "auth_handle", ESYS_TR)
File "/home/wcrobert/workspace/tpm2-pytss/src/tpm2_pytss/internal/utils.py", line 340, in _check_friendly_int
raise ValueError(
ValueError: expected auth_handle value of 1078035591 in class <class 'tpm2_pytss.constants.ESYS_TR'>, however it's not found.
> ESAPI: fix check on ESYS_TR in policy_secret

- test/test_crypto.py
Some types have changed their names in newer cryptography release, so add them to the tests
> test: add check for renamed cryptography types

- .github/workflows/publish_pkg.yaml
- .github/workflows/tests.yaml
- docs/index.rst
- setup.cfg
python 3.7 is unsupported as of 2023-06-27, so don't say we support it or test against it.
> setup: drop python 3.7

- src/tpm2_pytss/TCTILdr.py
- test/TSS2_BaseTest.py
- test/test_tcti.py
distros may place TCTI backend to different locations than the system libraries.
This commits makes the tests lookup the backend via `Tss2_TctiLdr_GetInfo` instead of of LD_LIBRARY_PATH.
> tctildr: use Tss2_TctiLdr_GetInfo to lookup tcti backend

- README.md
lgtm.com is no longer in service, so use CodeQL badges.
> README: replace LGTM with CodeQL

- test/test_crypto.py
- test/test_policy.py
Some Linux distributions have a limited set of supported ECC curves in openssl, so instead of finding a curve that fits everyone skip certain tests on those systems.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/527
> test: skip tests if ECC curves aren't supported.

- .github/workflows/tests.yaml
- docs/index.rst
- setup.cfg
Python 3.12 is released now, so test against it.
> test: test against python 3.12

- .readthedocs.yml
- docs/requirements.txt
readthedocks builds reports:
"""
Error
The configuration key "build.image" is deprecated. Use "build.os" instead to continue building your project. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os """
So switch to build.os.
> readthedocs: switch to os from image

- docs/api.rst
- docs/cryptography.rst
- src/tpm2_pytss/cryptography.py
- src/tpm2_pytss/internal/crypto.py
- test/test_cryptography.py
This implements the necessary interfaces to use RSA and ECC keys with the cryptography modules.
Enabling for example creating a CA or CSR with TPM-backed keys.
> cryptography: add module for using TPM keys with the cryptography module

- docs/maintainers.rst
- docs/project.rst
- fix docs build
- fix whitespace
- add maintainer key details
Fixes: #566
> docs: update maintainer key data

- src/tpm2_pytss/FAPI.py
- test/test_fapi.py
If exists_ok is True don't fail if the NV area already exists. Also return True if the area was created and False otherwise, in the same manner as create_key.
Fixes #574
> FAPI: support exists_ok for create_nv

- test/test_encoding.py
A update to libtpms changed the revision value, so accept the new value.
> test: update accepted TPM2_PT_REVISION values

- setup.py
GCC 15 uses -std=c23 by default, which causes pycparser to error out with "pycparser.plyparser.ParseError:
/usr/lib/gcc/x86_64-pc-linux-gnu/15/include/stddef.h:450:31: before: nullptr_t". As pcyparser only supports completely C99, this shouldn't be an issue.
> setup.py: Explicilty use C99 for preprocessing

- scripts/prepare_headers.py
Support for zephyr in tpm2-tss broke the removal of poll conditionals. So make the matching more flexible.
> scripts: fix regexp for poll stuff

- src/tpm2_pytss/internal/templates.py
- src/tpm2_pytss/utils.py
- test/test_utils.py
Clean up the code and make it more readable.
Support multiple names for different templates (EK-*, L-* and H-*). Add missing license header.
Fix the issue where EK-HIGH-RSA4096 had the wrong key size.
Closes #653
> utils: refactor EK template handling.

- pyproject.toml
- current version of setuptools (70.1+) does not need wheel at all
- older versions of setuptools would fetch wheel when building wheels (but not sdists)
> Do not require wheel for building

- src/tpm2_pytss/FAPI.py
The FAPIConfig context manager was not restoring environment variables to the state prior to entering the context. A consequence of that was that it was not possible to specify a config file using the TSS2_FAPICONF environment variable while running tests. The first test would use it, but then the variable would be cleared for subsequent tests, and it would revert back to trying the default paths.
> Restore environment when exiting FAPIConfig context

- src/tpm2_pytss/command_parser.py
- src/tpm2_pytss/constants.py
- src/tpm2_pytss/encoding.py
- src/tpm2_pytss/types.py
- test/test_types.py
To marshal/unmarshal an union a selector is needed. So add methods which takes the selector as an argument.
Closes #651
> types: add marshal/unmarshal methods for unions.

- docs/contributing.rst
Explain why we require the sign off and what it means.
> docs: add link to DCO text

- src/tpm2_pytss/types.py
- test/test_types.py
Allow comparing two stuctures by checking the output from marshal(). Only for structures as TPM2B_SIMPLE_OBJECT already has the equal dunder and unions would require a selector.
Closes #632
> types: add equal dunder for struct-based types

- .github/workflows/publish_pkg.yaml
ubuntu-20.04 is no longer available, so use the same values as for the coverage workflow.
> ci: fix pypi publishing workflow
