tpm2_pytss/binding.py, tpm2_pytss/esys.py, tpm2_pytss/exceptions.py, tpm2_pytss/tcti.py, tpm2_pytss/util/simulator.py, tpm2_pytss/util/swig.py
Fix all the current [LGTM alerts](https://lgtm.com/projects/g/tpm2-software/tpm2-pytss/alerts/), which are mainly import-related and very low-hanging fruit.
=> Fix LGTM alerts

setup.py, tpm2_pytss/binding.py, tpm2_pytss/util/swig.py
Fixes: #4
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> SWIG 4 Support

README.md, setup.py
Signed-off-by: John Andersen <johnandersenpdx@gmail.com>
=> setup: Fix missing library_dirs for pkg-config extention

tpm2_pytss/binding.py, tpm2_pytss/exceptions.py
Only useful if https://github.com/tpm2-software/tpm2-swig/pull/1 is merged
=> Add error handling for (un)marshal functions

tests/test_tpm2_error.py, tpm2_pytss/exceptions.py
Should fix https://github.com/tpm2-software/tpm2-pytss/issues/1
=> Add RC attribute to TPM2Error

tests/test_tpm2_error.py, tpm2_pytss/exceptions.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/2
=> Add parsing of response code fields

tests/test_tpm2_error.py, tpm2_pytss/version.py
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> tests: error: Use assertEqual

.gitignore, tests/base_esys.py, tests/test_binding.py, tpm2_pytss/binding.py, tpm2_pytss/util/calculate.py
Fixes: #19
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> binding: Support structures with array members

.ci/config.json.patch, .ci/run.sh, .gitignore, MANIFEST.in, README.md, setup.py, tpm2_pytss/binding.py, tpm2_pytss/config.json
dffml service dev release does not handle submodules correctly :(
=> Temporary fix for release issues

.ci/Dockerfile.tpm2-tss-python, .ci/run.sh
Signed-off-by: John Andersen <john.s.andersen@intel.com>
=> ci: Build extensions before docs

test/TSS2_BaseTest.py, test/esapi.py, test/fapi.py, tpm2_pytss/FAPI.py, tpm2_pytss/__init__.py, tpm2_pytss/utils.py
Add proof of concept bindings and tests for Fapi. For now, I did not include the Fapi to the `docs`, yet.
Feedback welcome!
**NOTE**: This PR sits on top of #58.
=> Add proof of concept for Fapi bindings and tests

test/test_types.py
=> test_types: fix class name

scripts/libtss2_build.py, scripts/prepare_headers.py, test/test_types.py, tpm2_pytss/types.py
Adds the bindings for libtss2-mu and attach them to the different objects.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/57
=> libtss2-mu bindings

test/test_types.py, tpm2_pytss/types.py
Support the various initializers from tpm2-tools routines tpm2_create
and tpm2_createprimary, such as:
- -G extended algorithm specfiers
- -g namealg
- -a object attributes
This does NOT support default attribute sets, so callers MUST specify
attributes. However, handy constants in the TPMA_OBJECT class specify
defaults for create and createprimary.
=> TPMT_PUBLIC: support tpm2-tools like initializers

setup.cfg, test/test_crypto.py, tpm2_pytss/ESAPI.py, tpm2_pytss/crypto.py, tpm2_pytss/types.py
Related to https://github.com/tpm2-software/tpm2-pytss/issues/88
=> types: add support for loading keys from PEM files.

tpm2_pytss/crypto.py
Fixes errors:
def public_from_pem(data, obj):
>       key = load_pem_public_key(data)
E       TypeError: load_pem_public_key() missing 1 required positional argument: 'backend'
tpm2_pytss/crypto.py:48: TypeError
backend set to None default didn't appear until cryptography >= 3.1.
See commit:
- https://github.com/pyca/cryptography/commit/24070d795443f9b01c926a9f7111e4405c0dbaa6
=> crypto: calls to cryptography < 3.1 require backend arg

.coveragerc, tpm2_pytss/crypto.py
I'm still battling the ci. But lets just start with adding a straight fix for the coverage.xml file
=> coveragerc: initial commit

test/test_crypto.py, tpm2_pytss/ESAPI.py, tpm2_pytss/crypto.py, tpm2_pytss/types.py
I added TR_GetName mostly to use it in the tests, but I hope it's useful for others as well.
Closes https://github.com/tpm2-software/tpm2-pytss/issues/104
=> implement getName

test/test_esapi.py, tpm2_pytss/ESAPI.py
=> ESAPI more testing

test/test_esapi.py, test/test_types.py, tpm2_pytss/ESAPI.py, tpm2_pytss/types.py, tpm2_pytss/utils.py
- Support construction of an object from the raw data of another object
- Support copy constructors
- Test ZGen_2Phase
- Test ECC_Parameters
=> More esapi testing and fixes

test/test_esapi.py, tpm2_pytss/ESAPI.py, tpm2_pytss/types.py
=> test: ESAPI EventSequenceComplete

test/test_esapi.py, tpm2_pytss/ESAPI.py
Add test for NV_ReadPublic and adds get_cdata to NV_DefineSpace.
@williamcroberts, do you one pull request per get_cdata call + test or can I add every test + get_cdata to this PR?
=> NV_ReadPublic test

test/test_esapi.py, tpm2_pytss/ESAPI.py, tpm2_pytss/crypto.py, tpm2_pytss/types.py
William Roberts (3):
test: remove unused variables from test_Vendor_TCG_Test
test: fix Vendor_TCG_TEST negative test
ESAPI: test Certify
=> Esapi testing: fixes and Certify command

README.md
=> Fixed 404 error on README.md

setup.cfg, test/test_tsskey.py, tpm2_pytss/tsskey.py
This is currently only basic mock code to show how I think TSS-keys could be handled.
Related to https://github.com/tpm2-software/tpm2-pytss/issues/88
=> tsskey.py: add class to handle tpm2-openssl keys

test/test_esapi.py, tpm2_pytss/ESAPI.py
As the simulator doesn't support these commands it's a bit hard to write useful tests, so I just check for TPM2_RC_COMMAND_CODE
=> Fieldupgrade tests

test/test_tsskey.py, tpm2_pytss/tsskey.py
Also fix a bug found with the tests
=> test_tsskey.py: test TSSPrivKey with persistent parent

test/test_esapi.py, tpm2_pytss/ESAPI.py
Tests for the functions under "Miscellaneous Management Functions"
=> Misc tests

test/test_makecred.py, tpm2_pytss/makecred.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/145
=> add python Duplicate/Wrap implementation

test/test_esapi.py, tpm2_pytss/ESAPI.py
Tests for the Dictionary Attack Functions
=> Dictionary tests

test/test_esapi.py, test/test_types.py, tpm2_pytss/ESAPI.py, tpm2_pytss/types.py
- ESAPI: SetCommandCodeAuditStatus use new check_handle function
- ESAPI: GetTime use new check_handle function
- ESAPI: GetCommandAuditDigest use new check_handle function
- ESAPI: GetSessionAuditDigest use new check_handle function
- ESAPI: use check_handle_type in Shutdown
- test: Esys_PCR_Allocate
- ESAPI: add expected to check_handle
- types: add to_string method for int types
- test: add checks to ESAPI PCR_Read
=> Esapi testing (ESys_PCR_Allocate, Esys_PCR_Read and cleanups)

test/test_esapi.py, tpm2_pytss/ESAPI.py
- ESAPI: use check_friendly_type in GetCap
- test: Esys_PCR_Reset
- test Esys_PCR_SetAuthValue
- test: Esys_PCR_SetAuthPolicy
=> test: Esys_PCR_SetAuthPolicy, Esys_PCR_SetAuthValue, Esys_PCR_Reset

test/test_crypto.py, tpm2_pytss/crypto.py, tpm2_pytss/types.py
This add support for handling SSH keys and providing different encoding choices for toPEM (pem, der and ssh).
Also included some general fixes and tests to increase test coverage.
=> More crypto encoding/decoding support

test/test_esapi.py, tpm2_pytss/ESAPI.py
=> test: Esys_PolicySigned

test/test_tcti.py, tpm2_pytss/TctiLdr.py
And fix the name and conf properties if None is passed for either.
=> Increase TctiLdr test coverage

test/test_crypto.py, test/test_esapi.py, test/test_fapi.py, test/test_makecred.py, test/test_tsskey.py, tpm2_pytss/ESAPI.py, tpm2_pytss/tsskey.py
=> Finish PEP8 formatting the ESAPI public API

tpm2_pytss/ESAPI.py
=> ESAPI: Add Typing through API

test/test_crypto.py, test/test_esapi.py, test/test_makecred.py, test/test_types.py, tpm2_pytss/ESAPI.py, tpm2_pytss/crypto.py, tpm2_pytss/makecred.py, tpm2_pytss/tsskey.py, tpm2_pytss/types.py
This should cover the last of the methods in types.py
Related to https://github.com/tpm2-software/tpm2-pytss/issues/163
=> Types PEP8

test/test_tsskey.py, tpm2_pytss/tsskey.py
PEP8ify the whole tsskey.py file and add docstrings.
=> tsskey: PEP8 TssPrivKey

test/test_esapi.py, tpm2_pytss/ESAPI.py
=> ESAPI: more documentation and parameter/return type updates

test/test_types.py, tpm2_pytss/types.py
More tests for coverage and some fixes for issues found while writing the tests
=> More tests and fixes

test/test_tsskey.py, tpm2_pytss/tsskey.py
Now the tests should cover all important code branches
=> More tests for TSSPrivKey

tpm2_pytss/crypto.py
As discussed in the  previous PR for key loading
=> crypto: change from checking for magic strings to using try-except blocks for key decoding

test/test_crypto.py, tpm2_pytss/types.py
Should make signature verification more accessible
=> types: attach verify_signature to TPMT_SIGNATURE

.github/workflows/publish_pkg.yaml
This PR utilizes and updates existing twine scripts/yamls to upload source dist to PyPi on tags.
=> Small updates to Twine PyPi upload

tpm2_pytss/ESAPI.py, tpm2_pytss/FAPI.py
Fixes for
* https://github.com/tpm2-software/tpm2-pytss/issues/255
* https://github.com/tpm2-software/tpm2-pytss/issues/252
=> Small bug fixes

test/test_types.py, tpm2_pytss/types.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/265
=> types: add tools-like string support for from_pem arguments

scripts/prepare_headers.py, tpm2_pytss/constants.py
- build: fix tpm2-tss deprecated master build
- constants: tpm2-tss TPM2_RS_PW -> TPM2_RH_PW
=> Fix tpm2 tss master build

CHANGELOG.md
=> CHANGELOG: update for 1.0.0-rc1

test/test_types.py, tpm2_pytss/constants.py, tpm2_pytss/internal/crypto.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/295
Took the handling of masked values in TPMA_* from https://github.com/tpm2-software/tpm2-pytss/pull/240 which should fix part of the issues in https://github.com/tpm2-software/tpm2-pytss/issues/318
Also added reference to tr_from_tpmpublic in the docstring for ESYS_TR as discussed in https://github.com/tpm2-software/tpm2-pytss/pull/317
=> Some fixes

CHANGELOG.md
=> CHANGELOG: update for 1.0.0

CHANGELOG.md
=> CHANGELOG: fix spelling of enhanced

test/test_esapi.py, test/test_types.py, tpm2_pytss/types.py
Support session contexts from tpm2-tools as well as function to marshal context to tpm2-tools format.
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/283
=> Tools context

test/test_encoding.py, test/test_types.py, tpm2_pytss/constants.py, tpm2_pytss/encoding.py, tpm2_pytss/types.py
Adding functionality to be able to serialize different TPM structures
=> Serialization

test/test_utils.py, tpm2_pytss/utils.py
Fixes https://github.com/tpm2-software/tpm2-pytss/issues/328
=> utils: add function to parse PCR values format from tpm2_quote

.ci/install-deps.sh, .github/workflows/tests.yaml
=> ci: test with and without fapi

CHANGELOG.md
=> CHANGELOG: update for 1.2.0

.github/workflows/tests.yaml
3.11 was just released, lets tests against that.
=> ci: test against python 3.11

.github/dependabot.yml
=> github: add dependabot updates

docs/index.rst
=> docs: mention Python 3.11 support

setup.cfg, test/test_encoding.py
=> Small fixes for 1.3

test/test_fapi.py, test/test_policy.py
Handle recent changes in tpm2-tss master so our tests don't break.
=> Fixes for tests against tpm2-tss master

src/tpm2_pytss/TCTI.py
The TCTI function pointers are designed to be called through a set of macros, for example the macro Tss2_Tcti_Receive. These macros perform some sanity checking of pointers and version numbers, match these in the Python code wrapper.
=> tcti: add common checks like header macros

src/tpm2_pytss/TCTI.py, test/test_tcti.py
=> py-tcti: support finalize

.lgtm.yml
=> lgtm: drop, going away for CodeQL

src/tpm2_pytss/ESAPI.py, src/tpm2_pytss/constants.py, test/test_esapi.py
Signed-off-by: malikabhi05 <abhishek.malik@intel.com>
=> ESAPI.py: Adding 1.59 updates

src/tpm2_pytss/FAPI.py
=> FAPI: drop unused import Dict

src/tpm2_pytss/internal/utils.py
Might fix https://github.com/tpm2-software/tpm2-pytss/issues/480
=> internal: check for sphinx not unittest.mock for docs workaround

src/tpm2_pytss/utils.py, test/test_utils.py
=> Add util functions to convert a credential from and to tpm2-tools format

.github/workflows/tests.yaml, README.md, docs/conf.py, docs/tcti.rst, scripts/libtss2_build.py, scripts/prepare_headers.py, setup.py, src/tpm2_pytss/TCTISPIHelper.py, test/test_tcti_spi_helper.py
Implement bindings to SPI helper TCTI and test.
=> TCTI: Implement bindings to spi-helper

README.md, docs/SECURITY.md
=> SECURITY.md: initial commit

CHANGELOG.md
Update changelog for new release candidate.
=> CHANGELOG: update for 2.2.0-rc1

src/tpm2_pytss/encoding.py
See https://github.com/tpm2-software/tpm2-pytss/issues/557
=> encoding: add deprecation warning to tools_encdec

scripts/prepare_headers.py
There are more upstream header file changes, so make sure we handle them correctly.
=> scripts: fix regex for header preparation

test/test_cryptography.py, test/test_policy.py
and fix the typo in the curve name in other places this is used.
=> Skip test using P-192 when not available

setup.py
Check if system is running BSD. If so, update declared C types accordingly.
I had to make these changes to get the package to build and install on FreeBSD 14.1. Creating this PR to save others the headache.
=> fix: FreeBSD build problems

src/tpm2_pytss/command_parser.py, src/tpm2_pytss/constants.py, src/tpm2_pytss/types.py, test/test_command_parser.py, test/test_types.py
=> Command response parser
